### ISSUE TITLE
When Invoke causes an error communicate that error to the caller

### ISSUE THREAD

**Issue by tylerslaton** [otto8-ai/otto8#12]
I sent an invoke request to Otto and got an empty response with 200OK.
```
POST - /invoke/<agent>

200OK 
```

This was confusing, I couldn't get any agent I had to respond to me. Eventually I looked at the runs and saw a lot of this.

```json
{
    "id": "r1znqms",
    "created": "2024-09-16T09:36:10-05:00",
    "threadID": "t17lpjw",
    "agentID": "a1fl2rs",
    "input": "",
    "state": "error",
    "error": "run encountered an error: prompt event occurred when prompt was not allowed: Message: Please provide your OpenAI API key:\nFields: [key]\nSensitive: true with error output: "
}
```

I would expect this to have caused the original invoke to at least have a non-200 status code. Ideally this would have also returned the error message.

**Comment by thedadams** [comment]
These errors now show up in the UI. If you change your OpenAI key to be something invalid and try to chat with an agent, you will see an error appear.

**Comment by sangee2004** [comment]
When testing with latest builds, 

1. Update OpenAI provider with an invalid OpenAI key 

2. Following errors are presented to the user when chatting with agents that have models set to "Use system Default"

```
failed to run: failed calling model for completion: error, status code: 502, message: failed to get model: default model alias "llm" is not configured
```
