### ISSUE TITLE
Creating an agent with "-r" option and using the same slug in agent file , results in another agent getting created.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#15]
commit id - d7fcd7e95

**Steps to reproduce the problem**

1. Create an agent with following file -`otto create -f agent1.toml`
```
slug: "searchinternet"
name: "searchinternet"
description: "Search Internet"
tools: ["https://github.com/gptscript-ai/answers-from-the-internet"]
prompt: "You are a good assistant.Wait for user to ask a question"
```
`otto agents` shows this entry
```
a1q6fjt   searchinternet        Search Internet                                                                 http://localhost:8080/invoke/seachinternet
```
2. Edit the `agent1.toml` file and fix the tool url to remove `https://` and update agent using `otto create -r -f agent1.toml`.

```
a1q6fjt   searchinternet        Search Internet                                                                 http://localhost:8080/invoke/seachinternet
a1k7hf8   searchinternet        Search Internet                                                                 http://localhost:8080/invoke/a1k7hf8
```
`otto agents` now shows 2 entries with invoke for the new entry having an id instead of the name`http://localhost:8080/invoke/a1k7hf8`

**Expected Behavior:**
When `-r` paramter is used to create an agent with an existing slug, this should result in updating the existing agent entry.

**Comment by thedadams** [comment]
The `-r` option has been removed. Moving to "Testing" for verification.

**Comment by sangee2004** [comment]
Closing this issue as we no longer support `-r` option.
