### ISSUE TITLE
Knowledge - Ingestion/sync threads relating to agents with knowledge file do not have agent information associated with it.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#188]
**Steps to reproduce the problem:**
1. Create an agent with knowledge files.
2. Notice that the ingestion threads do not have any information about the agent for which it was triggered.

```
r1qtws9                        t1ingest-8rvtp             completed   /Users/sangeethahariharan/Library/Application Support/otto/wo...   {"time":"2024-10-14T17:04:06.242338-07:00","level":"INFO","ms...   20 minutes ago
r1x6r8h                        t1ingest-82jrs             completed   /Users/sangeethahariharan/Library/Application Support/otto/wo...   {"time":"2024-10-14T17:03:25.681291-07:00","level":"INFO","ms...   21 minutes ago
```

When these threads get show in the UI in `Threads` view , they have the agent name as "unknown"

<img width="1423" alt="Screenshot 2024-10-14 at 5 26 25 PM" src="https://github.com/user-attachments/assets/d646219e-ee7d-4b44-91df-98112fd3e291">

**Comment by thedadams** [comment]
We explicitly decided not to put the agent information on these threads. Additionally, they are no longer displayed in the UI. I believe this addresses the main concern of this issue. Moving to "Testing" for verification.

**Comment by sangee2004** [comment]
Closing this issue as per https://github.com/otto8-ai/otto8/issues/188#issuecomment-2541828699.
