### ISSUE TITLE
Server startup should force users to set `OPENAI_API_KEY` env variable.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#197]
Server startup should force users to set `OPENAI_API_KEY` env variable.

Today we are allowed to start the server without this env variable set .

When chatting user will be prompted to enter openapi key which is not the expected workflow

<img width="518" alt="Screenshot 2024-10-15 at 10 32 07 AM" src="https://github.com/user-attachments/assets/2a0b3cd8-7f73-4c7c-ae48-b0a65906447b">

**Comment by thedadams** [comment]
This issue is no longer relevant because we changed the way this works. Moving to test for verification.

**Comment by sangee2004** [comment]
When server is started without OPENAT_API_KEY , user is not allowed to create new agents and is presented with following message asking to configure model providers:

<img width="1149" alt="Image" src="https://github.com/user-attachments/assets/04772e74-0f2b-4f60-942f-f97410988431" />

Even if user created an agent at this time using CLI , he will be presented with the following error message when chatting with the agent

```
failed to run: failed calling model for completion: error, status code: 502, message: failed to get model: default model alias "llm" is not configured
```
