### ISSUE TITLE
Knowledge UI - Scroll bar is not rendered as straight line. 

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#275]
**Steps to reproduce the problem:**

 Scroll bar is not rendered as straight line in Notion, website and OneDrive pages.
Notice that they curve with the file list grids.

https://github.com/user-attachments/assets/81593dc7-a7ba-4eb5-bb93-4d1b4d9a9a57

**Comment by thedadams** [comment]
This UI no longer exists. I believe this can be closed. Moving to "Testing" for verification.

**Comment by sangee2004** [comment]
Closing this issue.
