### ISSUE TITLE
Log statements are presented in the console for some commands like `otto create` and  `otto delete` and not for others.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#28]
For some commands like otto create , otto delete , i see log statements being printed in the console. 
This is not seen in other cases like `otto create -f <filename>`  , `otto edit <agent-id>` .
```
 % otto create    
 INFO  Creating an agent

You are about to create an agent. An agent is AI that will respond to user input
according to the instructions you provide.

Enter the instructions: You're a friendly assistant

 INFO  Agent created.
 INFO  
 INFO  ID: a1zbbfj
 INFO  URL: http://localhost:8080/invoke/a1zbbfj

You can now interact with your new agent by running:

CLI:  otto invoke --chat a1zbbfj Hello
cURL: curl -d Hello http://localhost:8080/invoke/a1zbbfj
```
```
 % otto delete a1zbbfj
INFO[0000] Agent deleted: a1zbbfj    
```

Why are we showing log statements in some cases  and not for others ? If we do want to show the logs , we should also be showing it for  `otto create -f <filename>`  and `otto edit <agent-id>`
```
otto create -f agent1.toml
Agent created: a1p4cgf
```

```
otto edit a1p4cgf
Agent updated: a1p4cgf
```

**Comment by thedadams** [comment]
I am not able to reproduce this with the latest version of the Otto8 CLI. Moving to test for verification.

**Comment by sangee2004** [comment]
When testing with latest builds , `otto create` and `otto edit` also dont show any log messages 

```
 otto8 create
Select a type to create: 
  > Agent
Created agent: a1z59cj
```

```
 % otto8 edit  a1z59cj
Agent updated: a1z59cj
```
