### ISSUE TITLE
UI - Show proper error message to user when tool creation fails.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#295]
**Steps to reproduce the problem:**
1.  Try to create new tool  with tool name having uppercase like

<img width="581" alt="Screenshot 2024-10-23 at 2 00 20 PM" src="https://github.com/user-attachments/assets/a99a74b8-fae0-4b81-a4a7-24ae91659a94">

This results in tool creation to fail and `422 post error` notification pops up.

**Expected Behavior:**
Provide a proper error message to user indicating what the problem is.

**Comment by ryanhopperlowe** [comment]
Looks like a duplicate of #502 

@sangee2004 - can you close this if that is the case?

**Comment by sangee2004** [comment]
Closing this issue . 
There is no name that needs to be entered when registering a tool now and #502 covers the error handling part of this issue.
