### ISSUE TITLE
Browser - Takes 3 -4 minutes for getting responses.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#370]
**Steps to reproduce the problem:**
1. Create an agent with Browser tool.
2.Ask to do the following in 1 prompt
```
Go to cnn.com. Click on entertainment link. Get the latest news .
```
3. It took 3 -4 minutes for the response to be received.

Debug logs - [calls (87).json](https://github.com/user-attachments/files/17577335/calls.87.json)

4. I had this chat which took about 1.4 minutes to respond.
```
go to world link and get the latest news
```
Debug logs - [calls (88).json](https://github.com/user-attachments/files/17577391/calls.88.json)

**Comment by njhale** [comment]
@sangee2004 getting the content of a page seems reasonably fast now.

For example, the `Get Page Contents` call triggered by the prompt "Get the content of the hackernews home page" takes ~5 seconds to finish on https://test.otto8.ai.

Could you test out the individual tool calls to see how quickly they respond?

It may just be that prompts requiring complex navigation that involve a sequence of multiple tool calls takes longer, but I'm seeing the individual calls respond quickly now.

**Comment by njhale** [comment]
cc @cjellick
