### ISSUE TITLE
Outlook Calendar - When responding to calendar invites , we see "Respond to Event" being called twice and LLM reports having problem finding the event.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#378]
**Steps to reproduce the problem:**

1. Create an agent with Outlook Calendar bundle.
2. Chat with the agent and respond to a meeting request with some message

Message gets sent out as expected and calendar entry reflects the right state.

But i see 2 calls to "Respond to Events" being made and LLM reports having problem finding the event.

<img width="718" alt="Screenshot 2024-10-30 at 2 12 56 PM" src="https://github.com/user-attachments/assets/edf9e213-8fdb-4222-9f1b-4cce82315f08">

Debug logs - [calls (96).json](https://github.com/user-attachments/files/17579219/calls.96.json)

**Comment by g-linville** [comment]
Not 100% sure, but I think this one may have been fixed, and it's worth testing to find out.

**Comment by sangee2004** [comment]
This issue is not seen anymore. I am not able to see the message being sent in the event accept email  which is tracked in https://github.com/otto8-ai/otto8/issues/859 .
