### ISSUE TITLE
UI - Outlook Mail Tool - Clicking the sender email mailto link does nothing.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#383]
**Steps to reproduce the problem:**

1. Create an agent with outlook mail bundle.
2. Ask to list emails

Notice that clicking the sender email link does nothing.

<img width="555" alt="Screenshot 2024-10-30 at 4 31 16 PM" src="https://github.com/user-attachments/assets/ccdd418b-8217-449b-9160-9cbceb3249b7">

**Expected Behavior:**
It should may open the a compose email page with "To" address being pre populated with the sender email.

**Comment by ryanhopperlowe** [comment]
@cjellick @sangee2004 - can this be closed?

**Comment by cjellick** [comment]
If you think an open issue has been addressed or is no longer valid, just set the project status to Testing and add a comment explaining the situation to @sangee2004. She retest or close or whatever the appropriate next steps are.

**Comment by sangee2004** [comment]
@ryanhopperlowe I am seeing this work when I have the outlook set a default in chrome.

<img width="1215" alt="Screenshot 2024-12-02 at 1 01 08 PM" src="https://github.com/user-attachments/assets/cfa4ca0e-3363-4405-9abf-2bec547e28b9">
