### ISSUE TITLE
Knowledge - Ingestion progress status  is not updated as expected when Ingestion is in progress.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#387]
**Steps to reproduce the problem:**
1. Create an agent and add knowledge from `acorn.io`
2. Wait for all files to be scraped and then click on "Ingest All"
3. Look at ingestion progress.
Notice that ingestion progress is not reported as expected and the reported counts remain the same.
<img width="965" alt="Screenshot 2024-10-30 at 10 10 37 PM" src="https://github.com/user-attachments/assets/fd382c24-a2ca-41c0-bef0-76d2afdc675d">

Once you close the website page, notice that the  ingested count reported in the Agent detail page will get refreshed with incremented ingested count.

**Comment by StrongMonkey** [comment]
@sangee2004 I think this is no longer valid

**Comment by sangee2004** [comment]
Closing this issue
