### ISSUE TITLE
UI - Issues with workflow relating to configuring custom githib oauth app.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#402]
**Steps to reproduce the problem:**
1. Configuring custom githib oauth following the instructions and choose `choose Replace Configuration` option in the last step.

After this i am brought back to Configure GitHub OAuth App page where i dont see the client id and secret set anymore .

**Expected Behavior:**
I should be presented with `Successfully configured Github OAuth App` page.

2. Call back url in the setup instruction is incorrect  - Should have been  for`https://test.otto8.ai/` instead of local host.
<img width="602" alt="Screenshot 2024-10-31 at 12 09 05 PM" src="https://github.com/user-attachments/assets/e840684d-fe1b-45be-a41a-4dc50ef1726e">

3. When i try to change the existing custom configurations using `Replace Configuration` option and submit the changes , i am presented with this overlapped pages

<img width="627" alt="Screenshot 2024-10-31 at 11 59 50 AM" src="https://github.com/user-attachments/assets/85ad75f0-8c9d-4c77-a369-4bf08b8b55cd">

4. With custom github aouth set , chatting with an agent with github tools  results in oauth workflow presented to the custom github aouth app as expected.

But i see the following error when trying to use it

<img width="1198" alt="Screenshot 2024-10-31 at 12 14 00 PM" src="https://github.com/user-attachments/assets/8f1d2822-03bb-4349-91a8-cddfdfae9dce">

**Comment by ryanhopperlowe** [comment]
@sangee2004 @cjellick - looks like this issue has been fixed. Moving to testing

**Comment by sangee2004** [comment]
All issues tracked here are fixed when testing with latest builds.
