### ISSUE TITLE
Knowledge - Scraping of files reports failure relating to "signal: killed"

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#441]
**Steps to reproduce the problem:**

1. Create an agent with knowledge files added using "Website" option for `https://ranchermanager.docs.rancher.com/`
2. There are about 6070 files that got scraped last time I had tested this - https://github.com/otto8-ai/otto8/issues/135

I see the following error reported after scrapping about ~3000 files.

<img width="1218" alt="Screenshot 2024-11-05 at 9 14 04 AM" src="https://github.com/user-attachments/assets/eebd6e44-07de-464e-b6a1-2894cde5a887">

**Expected Behavior:**
Scraping of all 6000+ files should be successful.

Related slack thread - https://acorn-io.slack.com/archives/C07FZ46QA2J/p1730826800094579

**Comment by cjellick** [comment]
@sangee2004 are you still able to repro this?

**Comment by sangee2004** [comment]
@cjellick I have not seen this error for sometime now.

Clising this issue for now. Will open a new issue if I see this error again.
