### ISSUE TITLE
Knowledge - filetype `.pages` - Not able to get the expected answer from knowledge files (possibly due to unsupported file type)

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#469]
**Steps to reproduce the problem:**
1. Create an agent with local file - https://acorn-io.slack.com/files/U04JJJXBN4V/F07V72YCA2E/storyfriendship.pages 
2. Ask the following - "Who are the main characters in Friendship story"
<img width="533" alt="Screenshot 2024-11-06 at 9 12 18 PM" src="https://github.com/user-attachments/assets/806fd0d5-5428-44d8-b565-96ae8e70e7aa">

Debug logs - [calls - 2024-11-06T211249.264.json](https://github.com/user-attachments/files/17656283/calls.-.2024-11-06T211249.264.json)

3. Add `Knowledge Description` as "A collection of documents relating to stories." to this agent.
4. In a new thread, the same question - "Who are the main characters in Friendship story" is still not able to get the right response and provides this response `The main characters in the "Friendship" story are not specified in the available data. If you have more details or context about the story, I might be able to assist you further.` 

Debug logs - [calls - 2024-11-06T211653.834.json](https://github.com/user-attachments/files/17656332/calls.-.2024-11-06T211653.834.json)

**Comment by cjellick** [comment]
I think you missed my point @iwilltry42  - I believe this file, which has the extension .pages, is not being ingested properly. But, we are allowing it to be ingested. Knowledge is returning nothing for it. If it returned the whole doc, it would probably work fine (and if you do a pdf with the same context as the .pages file it works fine).

Are we handling `.pages` correctly? Id be fine if we just properly rejected them and said we could not ingest them

**Comment by iwilltry42** [comment]
@cjellick - `.pages` has a mimetype of `application/zip` which is why we try to treat it like a ZIP archive.
I would vote to just not support archives at all anymore for ingestion.
That way we fend off "Zip bombs" and avoid mistreatments like this one based on the mimetype. (Lots of filetypes are archives - same goes for e.g. .docx)

**Comment by cjellick** [comment]
@iwilltry42 let's just drop support for archives. Don't bother adding support for pages. We can do that when a customer requests it.

**Comment by sangee2004** [comment]
Able to get retrieve information from `.pages` files.
