### ISSUE TITLE
knowledge - UI - No way for the users to know about ingestion errors unless they scroll thru the file list where the errors are reported.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#472]
I tried to "Ingest" all files from a website - `acorn.io` which resulted in couple of ingestion failures.

There is no obvious indication that there was any indication error when looking at this page.

<img width="1035" alt="Screenshot 2024-11-07 at 9 27 44 AM" src="https://github.com/user-attachments/assets/8002183f-a3f2-4519-a7c0-cc118fa6b07b">

The user will know about this only when they scroll thru the file list to see this information.

It would be good to surface this information in the Status field.

**Comment by StrongMonkey** [comment]
My suggestion:

Should we give a summary of status once sync is done. Something like 68 files added, 5 files not supported and 4 files errored.

**Comment by sangee2004** [comment]
Ingestion error count now is bubbled up at the folder level.

<img width="1112" alt="Image" src="https://github.com/user-attachments/assets/b394386f-f6f5-4da5-a0d4-8eafab83a478" />
