### ISSUE TITLE
UI - Provide some confirmation when registering tool succeeds.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#481]
**Steps to reproduce the problem:**
1. Register a tool.
Notice that once it is registered , the `Create New Tool Reference` pop up page dismisses and we are in the tools list view.
The tool gets added at the end of the tool list. User needs to scroll all the way down to be able to see it.

It would be good to provide some confirmation to the user that the tool was added successfully. Or we should be able to take him to the newly registered tool in the tool list.

**Comment by cjellick** [comment]
Id like user added tools to be at the top.

**Comment by sangee2004** [comment]
Registered tool now shows up at the top of the tool list.
<img width="434" alt="Image" src="https://github.com/user-attachments/assets/246d833c-4bcb-4d09-a588-acbc87c11cfb" />
