### ISSUE TITLE
UI - Chat messages and response was not presented in the chat window until manual refresh.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#484]
I was chatting with an agent which was responding for queries as expected.
After couple of chat message , any chat message i sent was not getting displayed in the chat window and also there was no response displayed.

I see `invoke` calls succeed during this time
```
https://test.otto8.ai/api/invoke/a1r7z98/threads/t1wlc2n
Request Method:
POST
Status Code:
200 OK
```
Also see event stream show the responses. But chat window did not show message/responses.

<img width="1466" alt="Screenshot 2024-11-07 at 6 15 04 PM" src="https://github.com/user-attachments/assets/b3337fd7-c355-495e-8c80-88b46a7e3b43">

https://github.com/user-attachments/assets/41f7a1fa-80d7-4ea6-a85c-886db9aa4544

Once i refreshed the thread , all the chat messages showed up.

**Comment by cjellick** [comment]
if you have seen this since, can you close

**Comment by sangee2004** [comment]
I have not been able to reproduce this issue since the time I saw it.

Closing this issue for now.
Will open a new issue if I see this behavior again.
