### ISSUE TITLE
Images in the Workspace are not displayed

### ISSUE THREAD

**Issue by cloudnautique** [otto8-ai/otto8#497]
When generating an image with the image gen tool, or taking a screenshot from the browser the images are broken in both the admin ui chat and user ui chat interfaces.
![Screenshot 2024-11-08 at 2 54 18 PM](https://github.com/user-attachments/assets/4ab74e27-0201-47a7-b03d-82f0d02865e3)
![Screenshot 2024-11-08 at 2 55 13 PM](https://github.com/user-attachments/assets/66786032-a722-4bbc-8fa7-b3d89d214424)

**Comment by njhale** [comment]
@sangee2004 Fix for the browser merged.

**Comment by sangee2004** [comment]
Able to see  the image from browser screenshots displayed in chat as expected.
![Image](https://github.com/user-attachments/assets/1c9112a3-15d5-4081-9bc9-d952e1f59887)
