### ISSUE TITLE
User is not provided with any error message when register tool fails 

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#502]
**Steps to reproduce the problem:**

1. Use` Register New tool` option to register a new tool.

Tool registration fails due to https://github.com/otto8-ai/otto8/issues/501

In this case api fails with `[ToolReference.otto.otto8.ai](http://toolreference.otto.otto8.ai/) "github-com-sangee2004-gptscript-mytool" not found  error.` 

This error message is not presented to the user and the `Register New tool` pop page is still presented.

**Expected Behavior:**
User should be presented with this error message.

**Comment by ryanhopperlowe** [comment]
assigning @ivyjeong13 because it will provide a chance to work with how I setup error handling

**Comment by ivyjeong13** [comment]
I think we'll need to update the backend POST call to wait for if the reference has been successfully loaded:

When creating a tool:
POST Request Payload: /api/tool-references
```
{
    "reference": "github.com/ivyjeong13/gptscript/mytool",
    "toolType": "tool"
}
```

POST Response Payload: /api/tool-references: 200 Call
```
{
    "id": "github-com-ivyjeong13-gptscript-mytool-1",
    "created": "2024-11-27T15:03:54-05:00",
    "type": "toolreference",
    "name": "github-com-ivyjeong13-gptscript-mytool-1",
    "toolType": "tool",
    "reference": "github.com/ivyjeong13/gptscript/mytool",
    "active": true
}
```

Note: `error` is missing from the response.

When I reload the page, I see the tool has been updated with 'error' in GET /api/tool-references?type=tool
```
{
    "id": "github-com-ivyjeong13-gptscript-mytool",
    "created": "2024-11-27T15:01:23-05:00",
    "type": "toolreference",
    "name": "github-com-ivyjeong13-gptscript-mytool",
    "toolType": "tool",
    "reference": "github.com/ivyjeong13/gptscript/mytool",
    "active": true,
    "error": "run encountered an error: run encountered an error: status code 500 with error output: failed to load program: failed to get GitHub commit of ivyjeong13/gptscript at HEAD (fallback error exit status 128: remote: Repository not found.\nfatal: repository 'https://github.com/ivyjeong13/gptscript.git/' not found\n): 404 Not Found {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/commits/commits#get-a-commit\",\"status\":\"404\"}"
}
```

**Comment by sangee2004** [comment]
@ivyjeong13 I am testing  with version `v0.0.0-dev-91dcd716-dirty` and seeing the same behavior outlined in https://github.com/otto8-ai/otto8/issues/502#issuecomment-2504703461

I am adding a tool with invalid tool url - `github.com/sangee2004/gptscript/tree/main/mytool` in this case.

https://github.com/user-attachments/assets/700825e5-c270-4e7e-95ac-1dd54c70109b


Wanted to check if there are more fixes coming in to make the tool registeration failure more obvious ? I should not have to need to refresh the tools page to see  the tool failure which is presented in Red. Also would there be any error message presented to the user other than just showing error state ?

**Comment by sangee2004** [comment]
Earlier build I tested with had some build issues which prevented the latest commits to be built.

Tested with version - `v0.0.0-dev-f2db3321-dirty`. 
User is presented with error message when tool creation fails as expected.

![Image](https://github.com/user-attachments/assets/72b6e87e-9a85-457b-b4c9-33628d4a5770)
