### ISSUE TITLE
Not able to save images.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#514]
**Steps to reproduce the problem:**
1. Create an agent with Images tool bundle and workspace Files
2. Chat with the agent and ask following:
3. generate an image of cow
4. Save this image in file cow.png

This results in image being saved with content - "/api/threads/t18t2m9/file/generated_image_324b2a32.png"

```
          {
            "content": "ave this image in file cow.png",
            "role": "user"
          },
          {
            "content": "",
            "role": "assistant",
            "tool_calls": [
              {
                "function": {
                  "arguments": "{\"filename\":\"cow.png\",\"content\":\"/api/threads/t18t2m9/file/generated_image_324b2a32.png\"}",
                  "name": "workspaceWrite"
                },
                "id": "call_ejo80bgZTEJD44hDhSCPTAVQ",
                "type": "function"
              }
            ]
          },
          {
            "content": "Wrote 54 bytes\n",
            "name": "workspaceWrite",
            "role": "tool",
            "tool_call_id": "call_ejo80bgZTEJD44hDhSCPTAVQ"
          }
```

Debug logs - 
[calls - 2024-11-10T121811.761.json](https://github.com/user-attachments/files/17692951/calls.-.2024-11-10T121811.761.json)

**Expected Behavior:**
We should be able to save the binary contents of the image.

Note - This causes problem when other tools like vision wants to access this file like - https://github.com/otto8-ai/otto8/issues/431#issuecomment-2466826619

**Comment by cjellick** [comment]
@njhale was this addressed in someway by a revamp to the image gen tool that you did?

**Comment by njhale** [comment]
> ... it is just too big for the workspace read or write files to work with.

Another issue is that the `workspace_read` tool only supports reading files [containing valid UTF-8 data](, which rules out binary files like generated images anyway.

> @njhale was this addressed in someway by a revamp to the image gen tool that you did?

No it wasn't, but I think fixing this may be as simple as implementing a `workspace_copy` tool to support copying workspace files without round-tripping through the LLM.

@cjellick WDYT?

**Comment by njhale** [comment]
Implementing `workspace_copy` resolves this issue.

**Comment by njhale** [comment]
@sangee2004 the fix for this is now in `main`. Please check it out.

**Comment by sangee2004** [comment]
I am able to save the image successfully when testing with latest build.
