### ISSUE TITLE
Presented with unexpected message in the chat response.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#515]
When chatting with an agent to generate images , I am presented with unexpected message in the chat response after the image is presented.

Presented with unexpected message along with image respnse.
<img width="649" alt="Screenshot 2024-11-10 at 12 25 04 PM" src="https://github.com/user-attachments/assets/d01927f5-5ecf-4063-a135-b8ef52d0a969">

Related Slack conversation - https://acorn-io.slack.com/archives/C03FU91U4SX/p1731269417568039?thread_ts=1731269351.777689&cid=C03FU91U4SX

Note - 
The unexpected message does not clear on refresh and persists in the thread.
I see this behavior only in this thread and this issue is not reproducible.

**Comment by cjellick** [comment]
i believe this is addressed

**Comment by sangee2004** [comment]
I have not seen this behavior since the 1 time i noticed it.

Closing this issue .
