### ISSUE TITLE
Knowledge - Onedrive - When there are lot of files to be synced as part of initial sync , it takes about 3.5 minutes (600+ files) for the files to start showing up.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#538]
**Steps to reproduce the problem:**
1. Create an agent with onedrive knowledge link to corp docs (which has 600+ files)
2. When syncing the corp docs from one drive , the following state is presented for about 3 and 1/2 minutes before files can start showing up. 

<img width="1061" alt="Screenshot 2024-11-11 at 12 07 08 PM" src="https://github.com/user-attachments/assets/8716b1d7-99ce-4399-b1d6-2329ed38502a">

After this files start showing up
<img width="1037" alt="Screenshot 2024-11-11 at 12 10 28 PM" src="https://github.com/user-attachments/assets/f46a6407-898a-4813-bfdb-9b6683c3e741">

**Expected Behavior:**
We should be able to show some progress/ status during this time.

**Comment by StrongMonkey** [comment]
This is expected to take that longer since it takes quite some times to sync and get all item in the folder. I can provide some status update when it is trying to sync metadata from a big folder.

**Comment by sangee2004** [comment]
When testing with latest version of the tool , we start seeing syncing status  and folder structure start showing up after ~13 seconds.
