### ISSUE TITLE
Knowledge - Ingestion of audio (.m4a) and video(.mp4) files ( unsupported file types) stuck in "Ingesting" state forever.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#544]
Note this error may not be seen always
**Steps to reproduce the problem:**

1. Create an agent with knowledge from onedrive location - Corps Docs (600+ files)
2. Have `New Files Ingestion Policy` set to `Automatic`

There are many audio (.m4a) and video(.mp4) files which are unsupported file types that are stuck in "Ingesting" state forever.

Debug logs for run relating to loading files:
```
  "frames": {
    "1731364101": {
      "chatResponseCached": false,
      "currentAgent": {

      },
      "displayText": "Running Knowledge Loading from /otto8-tools/./knowledge/load.gpt",
      "end": "0001-01-01T00:00:00Z",
      "id": "1731364101",
      "input": "{\"input\":\"/Corp Docs/Recordings/2024-08-13 15.05.52 Matt Cunningham's Zoom Meeting/video1115294552.mp4\",\"output\":\".conversion/Corp Docs/Recordings/2024-08-13 15.05.52 Matt Cunningham's Zoom Meeting/video1115294552.mp4.json\"}",
      "inputContext": null,
      "llmRequest": {
        "command": [
          "/bin/sh",
          "-c",
          "exec ${GPTSCRIPT_TOOL_DIR}/bin/gptscript-go-tool load --flows-file=blueprint:otto --flow=ottoload \"ws://${INPUT}\" \"ws://${OUTPUT}\""
        ],
        "input": "{\"input\":\"/Corp Docs/Recordings/2024-08-13 15.05.52 Matt Cunningham's Zoom Meeting/video1115294552.mp4\",\"output\":\".conversion/Corp Docs/Recordings/2024-08-13 15.05.52 Matt Cunningham's Zoom Meeting/video1115294552.mp4.json\"}"
      },
      "llmResponse": null,
      "output": null,
      "start": "2024-11-11T22:32:37.733551349Z",
      "tool": {
        "arguments": {
          "properties": {
            "Input": {
              "description": "Input File",
              "type": "string"
            },
            "Output": {
              "description": "Output File",
              "type": "string"
            },
            "know_load_metadata": {
              "description": "Comma-delimited key=value pairs to be added to the metadata of the loaded document.",
              "type": "string"
            }
          },
          "type": "object"
        },
        "description": "Load a document, convert it to Knowledge JSON Format and store it to a file.",
        "id": "/otto8-tools/./knowledge/load.gpt:Knowledge Loading",
        "instructions": "#!${GPTSCRIPT_TOOL_DIR}/bin/gptscript-go-tool load --flows-file=blueprint:otto --flow=ottoload \"ws://${INPUT}\" \"ws://${OUTPUT}\"",
        "internalPrompt": null,
        "localTools": {
          "knowledge loading": "/otto8-tools/./knowledge/load.gpt:Knowledge Loading"
        },
        "modelName": "gpt-4o",
        "name": "Knowledge Loading",
        "source": {
          "lineNo": 1,
          "location": "/otto8-tools/./knowledge/load.gpt"
        },
        "workingDir": "/otto8-tools/knowledge"
      },
      "toolResults": 0,
      "type": "callChat",
      "usage": {

      }
    }
  },
  "spec": {
    "synchronous": true,
    "threadName": "t1-ks1fvwtj",
    "input": "{\"input\":\"/Corp Docs/Recordings/2024-08-13 15.05.52 Matt Cunningham's Zoom Meeting/video1115294552.mp4\",\"output\":\".conversion/Corp Docs/Recordings/2024-08-13 15.05.52 Matt Cunningham's Zoom Meeting/video1115294552.mp4.json\"}",
    "tool": "\"knowledge-load\""
  },
  "status": {
    "state": "running",
    "output": "",
    "endTime": null
  }
}
```

Related Slack conversation - https://acorn-io.slack.com/archives/C07FZ46QA2J/p1731366237867149

**Comment by sangee2004** [comment]
@iwilltry42 The files that were stuck  in "Ingesting" state can be seen in the slack conversation thread. Test environment was running at 100% cpu when ingestion was in progress . @StrongMonkey had killed all these ingestion runs to get test environment to get to usable state .

**Comment by iwilltry42** [comment]
@StrongMonkey given the Slack discussion it seems like this was actually an issue with the workspace API, right?
Because `knowledge load` will throw a `{"unsupportedFiletype": ".mp4 (video/mp4)"}` eventually.

**Comment by StrongMonkey** [comment]
@iwilltry42 I wasn't sure. The fact the process that were hanging was `knowledge load` process, and seems like they are getting stuck

**Comment by iwilltry42** [comment]
Yeah, `load` and `ingest` both read from the workspace and as far as I understood, that breaks with >50MB files.
So now you put that limit for scraping, right? So this shouldn't happen anymore? :thinking:

**Comment by StrongMonkey** [comment]
Yeah, I will eventually put limit when syncing files

**Comment by iwilltry42** [comment]
The only handle I'd have on knowledge side is this:

1. add a list of explicitly unsupported filetypes (bad to maintain) to check against based on file extension (works without reading the content from the workspace)
2. read only a couple of bytes from workspace for mimetype detection - needs feature in workspace API/sdk

**Comment by sangee2004** [comment]
Tested with latest builds.

We now allow for syncing files with a max size of 50 mb.

It takes very less time to mark a 50 mb .ma4 file as unsupported.

![Image](https://github.com/user-attachments/assets/97b7b746-723d-4273-aaa1-0c2585cf72b5)
