### ISSUE TITLE
No way to go back to `workflows` page when in thread list view for a specific workflow.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#567]
**Steps to reproduce the problem:**
1. From Workflows page , go to threads links for any workflow.
2. From this thread list view , click on "Home" option.
This takes us to agents list page.

https://github.com/user-attachments/assets/ead85cab-eae1-4a14-ac55-5941396a582c

**Expected Behavior:**
`Home` should take us workflows page or have another link to take up back to `workflows` page.

**Comment by thedadams** [comment]
A more general issue is: the breadcrumbs don't work as expected. Essentially, there currently isn't a way to "go back" only "go home". https://github.com/otto8-ai/otto8/issues/579 is a similar issue with going from the users page to the threads page.

**Comment by sangee2004** [comment]
This issue and the one mentioned in #579 are now addressed in latest builds.
