### ISSUE TITLE
Outlook mail - LLM response does not let the user know that there are more  emails returned  when email queries return more than 10 entries.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#572]
**Steps to reproduce the problem:**
1. Create an agent with outlook tool bundle.
2. Ask to return email list that will result in more than 10 emails being returned like `list emails from last 7 days`

LLM returns first 10 emails from the list.
There is no indication to the user that there are more emails though if I ask to return more emails like `list 5 more emails from the list` , it gets the next set of emails as expected.

**Expected Behavior:**
When LLM shows 10 emails when the returned email list is longer , it should also inform the user that there are more emails that the query has actually returned.

Debug calls - 
[calls - 2024-11-12T222820.981.json](https://github.com/user-attachments/files/17727510/calls.-.2024-11-12T222820.981.json)
[calls - 2024-11-12T222815.134.json](https://github.com/user-attachments/files/17727512/calls.-.2024-11-12T222815.134.json)

**Comment by drpebcak** [comment]
Are you saying that you are now seeing an issue with the outlook tool where it's repeating data over and over again in its response?

**Comment by sangee2004** [comment]
@drpebcak No.I dont see it repeat the same data again and again. 

LLM is not able to tell the users that there are more than the 10 emails that get listed when there are lot of emails to be returned. In this same scenario , LLM has been able to inform users about there being more emails.

I was pointing out that i was seeing better handling of data in case of `google sheets` tool than `xlsheet` tool.
