### ISSUE TITLE
Unpublishing an agent removes user tools

### ISSUE THREAD

**Issue by thedadams** [otto8-ai/otto8#587]
All of these steps are taken from the admin UI.

1. Create a new agent.
2. Add any bundle under the "User tools" section
3. Publish the agent under any available name
4. Unpublish this agent
5. Refresh the page

The bundle added under "User tools" will be removed.

**Comment by ryanhopperlowe** [comment]
@thedadams @sangee2004 - I'm not able to reproduce this. Are you still seeing this issue?

**Comment by sangee2004** [comment]
I have not been able to reproduce the issue mentioned in the bug when testing with latest build.
I continue to see the tool bundle added under "User tools" to be present even after unpublish.
