### ISSUE TITLE
Knowledge - Takes very log time (sometime 2 minutes) to show the website page with all synced/ingested files.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#598]
**Note** - This delay in  showing  the website page with all synced/ingested files is not seen all the time.

**Steps to reproduce the problem:**
1. Create an agent with knowledge from website - (In my case https://nginx.org/en/docs )
2. Once all files are synced , ingest all the files.

After few minutes , tried to open the agent and then edit the knowledge website.
Website page is shown without any knowledge files .

Notice that status is Synced and we have the "Last Synced" and "Duration" set. But `File Synced` and `File Added to Knowledge` show as 0.

<img width="1022" alt="Screenshot 2024-11-14 at 8 04 57 PM" src="https://github.com/user-attachments/assets/6162b1c8-4ac0-469c-8a59-c25ac11683d8">

After about 2 minutes,  i was able to see all files show up and  `File Synced` and `File Added to Knowledge` have the right values.

<img width="1028" alt="Screenshot 2024-11-14 at 8 07 19 PM" src="https://github.com/user-attachments/assets/4c08161a-1124-4a4b-80c8-58c1756af9f1">

This behavior is also seen when we have synced files (and have not ingested them yet).

I started recording this after I noticed the delay in loading( may be after 10 secs of loading this page). This recording shows another 20 seconds taken to load the files.

https://github.com/user-attachments/assets/549ff9db-0c30-4152-96b6-f74496489e73

**Comment by StrongMonkey** [comment]
@sangee2004 are you still seeing this issue? In test env, it is probably taking 3/4 seconds to load files. But as we discussed, the knowledge file api is a bottleneck right now because the server doesn't do any filtering on the database query so it is very effiffient. We need to change that.

**Comment by sangee2004** [comment]
@StrongMonkey Yes. I am seeing about 5 secc delay when trying to open knowledge source to list all files now. I have seen it take a max of up to 10 secs to load files (when there are 600+ files which will not be the case anymore since we cap to 250 files).


Should i log a different bug to track for the knowledge file api being the bottleneck  and close this issue?

**Comment by StrongMonkey** [comment]
Yes, This is expected. There is a known issue with knowledge files because backend doesn't do any filtering on database requests
