### ISSUE TITLE
When using Azure OpenAI, otto8 fails to start because OpenAI API key is not set

### ISSUE THREAD

**Issue by thoraxe** [otto8-ai/otto8#602]
I am using Azure OpenAI and want to use this with Otto8. https://docs.otto8.ai/configuration/model-providers documents how to use Azure OpenAI with Otto8. However, when setting the Azure-specific environment variables, I get the following error when running the container:

`OPENAI_API_KEY env is required to be set`

Setting an OpenAI API key allows the startup to complete, but then Otto8 tries to use OpenAI anyway under the covers.

Here is my container run:

```
podman run -it --name otto8 -p 8080:8080 -e "OTTO8_AZURE_OPENAI_MODEL_PROVIDER_API_KEY=XXXX" -e "OTTO8_AZURE_OPENAI_MODEL_PROVIDER_DEPLOYMENT_NAME=YYYY" -e "OTTO8_AZURE_OPENAI_MODEL_PROVIDER_ENDPOINT=ZZZZ" ghcr.io/otto8-ai/otto8:latest
```

**Comment by thedadams** [comment]
Hi @thoraxe. Thanks for raising the issue.

The `OPENAI_API_KEY` is definitely required. When you say that Otto8 tries to use OpenAI anyway, what do you mean?

**Comment by thoraxe** [comment]
The default configuration appears to be that OpenAI models are all present/configured and set as the defaults. If you set a "fake" OpenAI key to get past the startup error, and then ask a question in the Otto8 interface, you get an error because the OpenAI API key is bad. 

It's not until you go in and manually reconfigure Otto8 to use Azure OpenAI models as the default that things start to work.

If I'm using Azure OpenAI for embedding and inference, why would I need to configure an OpenAI key at all?  It makes it seem like using OpenAI is a hard requirement even if you want to use Azure OpenAI?

**Comment by thedadams** [comment]
Thank you very much for explaining.

For now, this is how things are intended to work. However, we will keep this issue open as we discuss how the product should evolve.

**Comment by thoraxe** [comment]
If you want me to convert this to an RFE -- if I have only configured Azure OpenAI environment variables, then the "startup" sequence should potentially configure no models (empty list of models), or pre-populate a sensible set of Azure-specific defaults.

At a minimum I think that the service/server should start without an OpenAI API key even if it means there will be other failures post-start.

**Comment by thedadams** [comment]
Thanks for that input! I will bring it to the team as we determine how to move forward.

**Comment by billabongrob** [comment]
I agree with @thoraxe - the app seems to work fine otherwise, if I just send in `-e OPENAI_API_KEY=foo` 
I don't think there should be a hard requirement for OpenAI here.  On the flip side, once the application starts, everything is set to the broken model provider.

**Comment by thedadams** [comment]
A small update: we are going to be significantly changing the way we are handling model providers and these environment variables. I think it's a nice approach to fix this issue.

**Comment by thedadams** [comment]
The changes for this have all merged and the new functionality is on `main`.

**Comment by sangee2004** [comment]
With latest builds we can start otto server without providing any model provider credentials - `docker run -d -p 8080:8080 ghcr.io/otto8-ai/otto8:main`

Using UI, users will be to configure any Model provider from `Model Providers` page and work with it.
