### ISSUE TITLE
Cannot change default model

### ISSUE THREAD

**Issue by thoraxe** [otto8-ai/otto8#603]
Attempting to change the default model always results in the following error:

`model gpt-4o is already the default model`

It appears that you have to first remove the default model setting before you can set a new default.

I think the user experience is potentially what's broken here -- trying to set a new default should warn the user that they are making the change and that it will affect other users. You should not get an error when attempting to set a new default that there is already a default set.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest build -   `"otto": "v0.0.0-dev-13e341a9-dirty"`

Able to change default model aliases without having to remove the current default settings.
