### ISSUE TITLE
502 <Model.otto.otto8.ai \"text-embedding-3-small\" not found\n>

### ISSUE THREAD

**Issue by thoraxe** [otto8-ai/otto8#607]
I'm trying to use text-embedding-3-small with Azure OpenAI. I have this configured in Otto8. I have deleted all other model configurations. The only two model configurations I have:

1. text-embedding-3-small as a text-embedding model
2. gpt-4o as the default as an agent

When attempting to ingest a knowledge document, an error occurs:

```
failed to ingest file: ingestion failed for at least one file: failed to add documents from file "ws://directory:///data/.local/share/otto8/workspace-provider/af4accb1-396c-4152-a027-d2be574a9783/.conversion/image-streams-manage.txt.json": couldn't add document '28a9c87f-a0f4-4ea3-9959-c219f8ab07e2': couldn't create embedding of document: error sending request(s): retry limit (5) exceeded or failed with non-retriable error(s): #1/5: 502 <Model.otto.otto8.ai "text-embedding-3-small" not found > (err: <nil>); #2/5: 502 <Model.otto.otto8.ai "text-embedding-3-small" not found > (err: <nil>); #3/5: 502 <Model.otto.otto8.ai "text-embedding-3-small" not found > (err: <nil>); #4/5: 502 <Model.otto.otto8.ai "text-embedding-3-small" not found > (err: <nil>); #5/5: 502 <Model.otto.otto8.ai "text-embedding-3-small" not found > (err: <nil>)
```

Is there a way to get more debug logging via environment variable? It's not clear what URL Otto8 is attempting to reach.

**Comment by thedadams** [comment]
Thanks for opening this issue. This is not yet supported, but a change has been submitted to make this possible: https://github.com/otto8-ai/tools/pull/212

**Comment by sangee2004** [comment]
Tested with latest version:
```
 "github.com/otto8-ai/tools": "53542f56c49e51c4f72ed0b89c9a666c697e96ec",
  "otto": "v0.0.0-dev+a23826b0"
```

Able to ingest knowledge files successfully using `text-embeddng-3-small` mode from `Azure OpenAI.` provider.

1. Configured Azure OpenAI model provider by going to `ModelProviders`->`Azure OpenAI model provider` and click on `settings` icon.
2. Add the following models with Azure OpenAI model provider by going to `Models` ->`Add  Model`
![Image](https://github.com/user-attachments/assets/9a51691f-4923-4892-91c4-55a9442dcda7)
3. Set all these model from `Azure OpenAI model provider` as default model aliases.
![Image](https://github.com/user-attachments/assets/86cec0ab-2910-4125-9f89-2be68432eeed)
4. Deleted all defaults models from OpenAI model provider ( This step is not needed. But i did this to prove that we will be able to test with out having any openAI models)
5. Create an agent and add  knowledge files.

Able to ingest knowledge files successfully.
