### ISSUE TITLE
Knowledge -  Knowledge tool error out when using Azure OpenAI model provider.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#614]
**Steps to reproduce the problem:**

1. Create following 3 models:
a. model with model providers as `Azure OpenAI` and target model as `gpt4-o` set as "default"
b. model with model providers as `Azure OpenAI` and target model as `text-embedding-ada-002`
c. model with  model providers as `Azure OpenAI` and target model as `text-embedding-3-small`

2. Create an agent with model set to `User System Default`
3. Add a local knowledge file.

Ingestion of fails with following error message which suggests that we are still using values set in `OPENAI_API_KEY` which is invalid in my case.

<code>
failed to ingest file: ingestion failed for at least one file: failed to add documents from file "ws://directory:///data/.local/share/otto8/workspace-provider/a7873e01-a4ac-4a6f-9503-6cd12f9c736e/.conversion/Holiday List_2024.pdf.json": couldn't add document '0427f4c0-69d1-4584-a4b8-a1c844442a79': couldn't create embedding of document: error sending request(s): retry limit (5) exceeded or failed with non-retriable error(s): #1/5: 401 <{ "error": { "message": "Incorrect API key provided: sk-test. You can find your API key at https://platform.openai.com/account/api-keys.", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" } } > (err: <nil>)
</code>

```
{
  "items": [
    {
      "id": "ea14c2d390e346b74fa1fecdd7214d1e637e166657007c8abdb390eb517d8ca3",
      "created": "2024-11-15T23:18:57Z",
      "type": "knowledgefile",
      "fileName": "Holiday List_2024.pdf",
      "state": "error",
      "error": "failed to ingest file: ingestion failed for at least one file: failed to add documents from file \"ws://directory:///data/.local/share/otto8/workspace-provider/a7873e01-a4ac-4a6f-9503-6cd12f9c736e/.conversion/Holiday List_2024.pdf.json\": couldn't add document '0427f4c0-69d1-4584-a4b8-a1c844442a79': couldn't create embedding of document: error sending request(s): retry limit (5) exceeded or failed with non-retriable error(s): #1/5: 401 \u003C{\n    \"error\": {\n        \"message\": \"Incorrect API key provided: sk-test. You can find your API key at https://platform.openai.com/account/api-keys.\",\n        \"type\": \"invalid_request_error\",\n        \"param\": null,\n        \"code\": \"invalid_api_key\"\n    }\n}\n\u003E (err: \u003Cnil\u003E)",
      "agentID": "a17t92x",
      "knowledgeSetID": "kst1-a17t92x",
      "approved": true,
      "lastIngestionStartTime": "2024-11-15T23:18:57Z",
      "lastIngestionEndTime": "2024-11-15T23:18:57Z",
      "lastRunIDs": [
        "r1wxcjl",
        "r1qvlvj"
      ],
      "sizeInBytes": 110918
    }
  ]
}
```

**Comment by sangee2004** [comment]
Tried the following steps where I am not creating any new model. But  updating the following 3 existing models and setting the provider to `Azure OpenAI` provider.
1. gpt4-o
2. text-embedding-ada-002
3. text-embedding-3-small

1. Create an agent with model set to `User System Default`
2, Add a local knowledge file.

Ingestion of fails with following error message 

<code>
failed to ingest file: ingestion failed for at least one file: failed to add documents from file "ws://directory/:///data/.local/share/otto8/workspace-provider/80042982-240f-41c5-a20a-de83fae036f7/.conversion/README.md.json": couldn't add document 'bf7426f3-6e21-4624-92cb-79da9c6c07f1': couldn't create embedding of document: error sending request(s): retry limit (5) exceeded or failed with non-retriable error(s): #1/5: 404 <{"detail":"Not Found"}> (err: <nil>)
</code>

**Comment by sangee2004** [comment]
Issues seen with Image generation tools:

**Steps to reproduce the problem:**
1. Modify the existing `dall-e-3` model entry to use `Azure Openai`  provider.
2. Modify` gpt-4o` model to use `Azure Openai`  provider and set it as default.
3. Create an agent with image bundle and ask to generate images.

This fails to generate images

<img width="716" alt="Screenshot 2024-11-15 at 4 51 32 PM" src="https://github.com/user-attachments/assets/1bc31d25-3a77-4b85-aa3c-08b0aa9f846a">


<img width="1001" alt="Screenshot 2024-11-15 at 4 52 24 PM" src="https://github.com/user-attachments/assets/f9a73660-0aee-4ef8-a3cb-d6de13c08766">


Debug logs - [calls - 2024-11-15T165241.266.json](https://github.com/user-attachments/files/17782764/calls.-.2024-11-15T165241.266.json)

**Comment by sangee2004** [comment]
Tracking the issue seen with image generation in - https://github.com/otto8-ai/otto8/issues/619

**Comment by thedadams** [comment]
This has changed significantly, but the underlying issue should be addressed.

**Comment by sangee2004** [comment]
Able to ingest knowledge files and retrieve information from them successfully using Azure OpenAI model provider.
