### ISSUE TITLE
Image generation tools errors out when using Azure OpenAI model provider.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#619]
**Steps to reproduce the problem:**
1. Modify the existing `dall-e-3` model entry to use `Azure Openai`  provider.
2. Modify` gpt-4o` model to use `Azure Openai`  provider and set it as default.
3. Create an agent with image bundle and ask to generate images.

This fails to generate images

<img width="716" alt="Screenshot 2024-11-15 at 4 51 32 PM" src="https://github.com/user-attachments/assets/1bc31d25-3a77-4b85-aa3c-08b0aa9f846a">

<img width="1001" alt="Screenshot 2024-11-15 at 4 52 24 PM" src="https://github.com/user-attachments/assets/f9a73660-0aee-4ef8-a3cb-d6de13c08766">

Debug logs - [calls - 2024-11-15T165241.266.json](https://github.com/user-attachments/files/17782764/calls.-.2024-11-15T165241.266.json)

**Comment by njhale** [comment]
This will require:
1. The `Generate Images` tool to consume the model environment variable (the exact naming of this variable is TBD)
2. Implementing the `/v1/images/generations` route in the model provider (in [here](https://github.com/otto8-ai/tools/blob/main/azure-openai-model-provider/main.py))

**Comment by cjellick** [comment]
@thedadams is this addressed?

**Comment by thedadams** [comment]
This will be addressed once https://github.com/otto8-ai/tools/pull/260 and https://github.com/otto8-ai/otto8/pull/781 are merged.

**Comment by sangee2004** [comment]
Able to generate images successfully when setting the default model aliases for `Image generation` to `dall-e-3` model from Azure OpenAI model provider.
![Image](https://github.com/user-attachments/assets/4ec3baab-ff0c-4d65-963e-0247e57b4cd2)
