### ISSUE TITLE
It takes about 10 seconds to list credentials for threads.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#621]
**Steps to reproduce the problem:**
I am testing in test env where I have already had a conversation with `otto` agent about github repos. 

1. Launch user ui for any agent (otto in my case).
2. Click on user profile icon . Notice that credentials is spinning for 10 seconds before we are able to present the credentials.

https://github.com/user-attachments/assets/618add9e-4adc-474d-9768-99bde8e141c0

**Comment by sangee2004** [comment]
@g-linville I also see a big delay before notion/onedrive sync is able to provide the oauth flow. Is this related to the same issue as well ?

https://github.com/user-attachments/assets/740e933b-60b7-44df-aef7-e9688ff33b3e

**Comment by g-linville** [comment]
The fix for this is merged and deployed to main.

**Comment by sangee2004** [comment]
Testing with latest version - 
```
  "github.com/kubernetes-sigs/aws-encryption-provider": "24ffc614b97e06b8fdcf62de2aedad0f9f3b5e7e",
  "github.com/otto8-ai/tools": "9abc7da7146cbd8448dca8ed11fde418482f2341",
  "otto": "v0.0.0-dev+b1a78bfe"
```

@g-linville Listing credentials for threads  from user ui very quick now.

But I am still seeing a big delay delay before notion/onedrive sync is able to provide the oauth flow.

https://github.com/user-attachments/assets/1ca13e77-3cc4-4d64-8e87-c2d6db1a5fea

**Comment by thedadams** [comment]
The notion/onedrive sync oauth flow is a separate issue and isn't related to listing credentials.

@sangee2004 Can we close this issue and open another for the new issue?

**Comment by sangee2004** [comment]
@g-linville mentioned that it could be related to the fix he was providing. So tracked it in the same issue.
Tracked notion/onedrive  related issue in https://github.com/otto8-ai/otto8/issues/635
