### ISSUE TITLE
Slack - User context tool gets called when we are chatting with an agent about things unrelated to slack.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#623]
**Steps to reproduce the problem:**
1. Create an agent with `Slack` and `github` tool bundles.
2. Chat with the agent, about anything unrelated to `Slack`

Notice that Slack User context tool gets called.
I see Slack User context tool  getting called even when I chat about `github` tool.

<img width="1143" alt="Screenshot 2024-11-18 at 1 33 09 PM" src="https://github.com/user-attachments/assets/9207a158-2905-45c6-be9c-57f39c25947b">

Note - This issue is also seen when creating an agent with just `Slack`  tool as well or an agent with slack and any other tool bundle.

I have seen this issue fixed as part of validating - https://github.com/otto8-ai/otto8/issues/492. But seeing it happen again.

**Comment by g-linville** [comment]
Merged.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest version of the tool.
