### ISSUE TITLE
When ingesting some website we see < 250 files being synced and no message given to the user about having reached the sync limit.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#625]
**Steps to reproduce the problem:**
1. Create an agent with knowledge from website - `intel.com`

Notice that only 229 files get synced and user is not presented with the message about having reached the sync limit . 
<img width="1021" alt="Screenshot 2024-11-18 at 2 54 02 PM" src="https://github.com/user-attachments/assets/2be86082-349a-49a7-801c-dc58f38c65e7">

**Expected Behavior:**
We should be able to sync a max of 250 files in this case and also present this message to the user -`You have reached the maximum number of files that can be synced`

**Comment by StrongMonkey** [comment]
This should be fixed

**Comment by sangee2004** [comment]
This issue is not seen anymore.
