### ISSUE TITLE
Knowledge - When using `Include All Files` to ingest all synced files , lot of files do not get approved and remain in "Excluded" state (probably after an ingestion failure).

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#626]
**Steps to reproduce the problem:**

1. Create an agent with knowledge file from onedrive location that has 600+ files.
2. Once sync is completed , Ingest all files using `Include All Files`

This results in ingestion of few files to fail which is tracked in - https://github.com/otto8-ai/otto8/issues/460#issuecomment-2484428975 and 1 file was stuck in ingesting state tracked in  - https://github.com/otto8-ai/otto8/issues/544

I also see that there are lot of files that have not yet been approved and remains in "Excluded" state. 
Not sure if ingestion failures could result in file approval to be blocked in this case.

Agent - https://test.otto8.ai/admin/agents/a1mz52w

**Expected Behavior:**
File approval for all files should succeed and ingestion for these files should be attempted.

**Comment by StrongMonkey** [comment]
@sangee2004 You should be able to retest this now.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest builds.
