### ISSUE TITLE
Notion - Not able to create pages with large content (~2700 characters).

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#627]
**Steps to reproduce the problem:**
1. Create an agent with notion bundle.
2. Asked to `Come up with a story about 3 beautiful duckings`
3. Asked to` Write this into a "Duckling" page under "my new Test page"`

The tool hits content length restriction.
<img width="496" alt="Screenshot 2024-11-18 at 5 32 12 PM" src="https://github.com/user-attachments/assets/d9b1fe9a-a6d6-48de-a581-50fb68dd1a30">

Debug logs - [calls - 2024-11-18T173459.831.json](https://github.com/user-attachments/files/17808052/calls.-.2024-11-18T173459.831.json)

Following error is seen for the tool call:
```
body failed validation: body.children[0].paragraph.rich_text[0].text.content.length should be ≤ `2000`, instead was `2780`
```

4. If i say - "Yes", it creates multiple pages.

<img width="506" alt="Screenshot 2024-11-18 at 5 35 27 PM" src="https://github.com/user-attachments/assets/23577d5e-00d5-41e9-b6d1-9eda8289f205">

Debug logs - [calls - 2024-11-18T173541.895.json](https://github.com/user-attachments/files/17808062/calls.-.2024-11-18T173541.895.json)

I am able to create a notion page with the contents provided by LLM in step2 using Notion UI with out any problems.

**Expected Behavior:**
Should be able to create a notion page that includes  all the contents from step2.

**Comment by tybalex** [comment]
@sangee2004 https://github.com/otto8-ai/tools/pull/266 please confirm if PR#266 fixed this issue.

**Comment by cjellick** [comment]
@tybalex you should move your issues to testing when theyre completed

**Comment by sangee2004** [comment]
Able to create 1 notion page with large content ( ~4000 characters) when testing with latest version of the tool.
