### ISSUE TITLE
Knowledge - Notion Sync does not fetch all pages.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#637]
**Steps to reproduce the problem:**
1. Create an agent with knowledge files from notion and select a page that has many child page  (which have other child pages)  (`General` in my case with `Engineering` and `Demo` pages selected during the oauth flow)

Once initial sync is completed, we would see only 2 files , Engineering.md and Demo.md listed. This issue is tracked in https://github.com/otto8-ai/otto8/issues/200. 

2. Use `Sync Now` option again. 
This will result in all child pages/folders getting synced.

Notice that once sync is completed , we do not see all pages being synced. I see only a total of 47 pages being synced.

In my case I see many pages ( including their child pages) not being synced like `Product Management`, `Developer How-Tos` .
`Archive - Old Acorn Stuff` page is synced. But no child pages for this is synced.

Also i did not see any pages under `Demo` getting synced

Agent - https://test.otto8.ai/admin/agents/a1fjnw4

3. Tried to create agent with knowledge files from only  `Engineering` and see the same set of files being synced as in step 2.

Agent - https://test.otto8.ai/admin/agents/a1p4nkd

4. Tried to create agent with knowledge files from only  `Demo` and see that i was able to get all pages under demo synced.

Agent - https://test.otto8.ai/admin/agents/a1wjftt

**Expected Behavior:**
All pages (including child pages should be synced).

**Comment by StrongMonkey** [comment]
Should be fixed already

**Comment by sangee2004** [comment]
Tested with latest build.

We are now getting 197 files synced when `General` (along with `Engineering` and `Demo` )pages get selected.
