### ISSUE TITLE
Knowledge - Restrict syncing files larger than certain size to prevent 100% cpu consumption on ingestion of these files.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#642]
When trying to ingest knowledge files ( from onedrive location in my casew) which have audio and video files > 100 MB large, it results in 100% cpu consumption making the server unresponsive.

**Expected Behavior:**
We should be able to restrict syncing files larger than certain size to prevent 100% cpu consumption on ingestion of these files.

**Comment by StrongMonkey** [comment]
I put a fix where files that are bigger than 50 mb won't be synced

**Comment by sangee2004** [comment]
Tested with latest build.

We sync only files that are less than 50 mb now.
