### ISSUE TITLE
Knowledge - Not able to ingest pdf files with images using Azure OpenAI provider.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#648]
**Steps to reproduce the problem:**
1. Started otto server with env variable needed for Azure OpenAI provider. (Note - I have an invalid key set for `OPENAI_API_KEY`)
2. Changed the provider for existing `gpt-4o` and `text-embedding-3-small` models to  `Azure OpenAI provider`
3. Create an agent with local knowledge file - [Holiday List_2024.pdf](https://github.com/user-attachments/files/17837685/Holiday.List_2024.pdf)
Ingestion of this file succeeded.
4. Add another local knowledge file which has images - [Reunion-Under-The-Stars.pdf](https://github.com/user-attachments/files/17837696/Reunion-Under-The-Stars.pdf)

Ingestion of this file, fails with following error which shows  `OPENAI_API_KEY` being used for loading the documents.
<code>
failed to load documents from file "ws://Reunion-Under-The-Stars.pdf" using loader "": error sending image to OpenAI: OpenAI OCR error sending request(s): retry limit (5) exceeded or failed with non-retriable error(s): #1/5: 401 <{ "error": { "message": "Incorrect API key provided: sk-test. You can find your API key at https://platform.openai.com/account/api-keys.", "type": "invalid_request_error", "param": null, "code": "invalid_api_key" } } > (err: <nil>)
</code>

**Expected Behavior:**
Ingestion of file should succeed by using Azure OpenAI provider model.

**Comment by cjellick** [comment]
@thedadams This should be addressed by the revamp to model listing that you did the backend for and @ryanhopperlowe is doing the frontend for?

**Comment by thedadams** [comment]
Yes, that's correct.

**Comment by ryanhopperlowe** [comment]
should be fixed by #744

**Comment by ryanhopperlowe** [comment]
#744 is merged to main now.

@thedadams - can you move this to `testing` when the backend portion is finished?

**Comment by cjellick** [comment]
@ryanhopperlowe backend is already in, right? you would not have been able to do frontend without it

**Comment by thedadams** [comment]
The final fix was: https://github.com/otto8-ai/tools/pull/261

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest builds:

Default models was set  to Azure OpenAI provider model for all model Aliases.

![Image](https://github.com/user-attachments/assets/20a0fb49-9cb0-4265-a294-ca7d7e0c2118)


Able to successfully  Ingest pdf files with images.

Was also able to ingest knowledge files from website successfully.
