### ISSUE TITLE
Knowledge - File size shown for synced file is reported incorrectly ( little more than actual size ).

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#659]
**Steps to reproduce the problem:**
1. Create an agent with knowledge file from onedrive location.
2. Wait for the files to be synced.
3. Notice that the file size reported in synced file list is little more than actual size.

<img width="1246" alt="Screenshot 2024-11-21 at 3 10 13 PM" src="https://github.com/user-attachments/assets/e29e860a-e651-4fe3-8890-ff9d18c2f34b">

from onedrive

<img width="1012" alt="Screenshot 2024-11-21 at 3 12 19 PM" src="https://github.com/user-attachments/assets/87f0b0ce-4f02-4c68-88bd-88baa2cf5a37">

**Comment by StrongMonkey** [comment]
@cjellick yep, just some frontend calculation bug

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest build.
