### ISSUE TITLE
Knowledge - Notion - Parent pages for the selected file folders should be moved under the folder.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#667]
**Steps to reproduce the problem:**
1. Create an agent with knowledge files from notion.
2. Once all the files are synced , notice that  parent pages  (.md) for the selected file folders (during the oauth flow) is presented in the same level as the related folders.

In my case , I had selected `Engineering` and `Demo Stuff` folders during the oauth flow.

<img width="1016" alt="Screenshot 2024-11-22 at 2 59 24 PM" src="https://github.com/user-attachments/assets/c8b28733-9838-41da-94c6-7b46f5b120fa">

**Expected Behavior:**
Move  `Engineering.md` file under `Engineering` folder and `Demo Stuff.md` file under `Demo Stuff` folder.

**Comment by cjellick** [comment]
Yeah..weird one since technically they are not children, but @StrongMonkey what do you think? Can that relationship even be figured out?

**Comment by StrongMonkey** [comment]
yes, i talked to sangeetha, it might makes sense to have the parent page be included as root page in the folder itself. Need some tweaking

**Comment by sangee2004** [comment]
Tested with version:
```
 "github.com/otto8-ai/tools": "194596a6577309f0c5f0e905a51f1058a066f9ad",
  "otto": "v0.0.0-dev-f2db3321-dirty"
```

Parent pages for the selected folders are now included as root pages under the folder list.
