### ISSUE TITLE
Knowledge - Additional root level folder sync is shown when syncing some websites.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#675]
**Steps to reproduce the problem:**
1. Create an agent and add knowledge files from cry.org
2. Notice that there is `www.ukcry.org` folder that also gets synced.

<img width="981" alt="Screenshot 2024-11-25 at 3 27 49 PM" src="https://github.com/user-attachments/assets/1b1a5c5e-cec1-481b-b364-a37e479acd3a">

**Expected Behavior:**
Ideally we dont expect any folder with domain other than `cry.org` to get synced.

**Note** - Also notice that this folder never shows "Included" state even after it was included ( and files have been ingested successfully).

**Comment by sangee2004** [comment]
This behavior is also seen when testing with `intel.com`
<img width="971" alt="Screenshot 2024-11-26 at 6 50 49 AM" src="https://github.com/user-attachments/assets/e3115f88-dd67-47b1-b187-c87e796f9934">

**Comment by sangee2004** [comment]
I am seeing this behavior with `coral.org` as well:

<img width="991" alt="Screenshot 2024-11-26 at 1 44 30 PM" src="https://github.com/user-attachments/assets/45379033-25ea-4b69-9ab3-9bdcd55acc07">

**Comment by StrongMonkey** [comment]
@sangee2004 the intel example are caused by redirect. The original URL belongs to the same domain but redirects to comsumer.intel.com and edc.intel.com. Likely it is the same case for coral.org. The cry.org case is a bug where should be fixed in the PR

**Comment by sangee2004** [comment]
Blocked on testing this issue because of sync not succeeding from `cry.org` - https://github.com/otto8-ai/otto8/issues/743

**Comment by sangee2004** [comment]
`www.ukcry.org` folder does not get synced when testing with latest build.
