### ISSUE TITLE
UI - Tool Icon Inverted in tool catalog

### ISSUE THREAD

**Issue by ryanhopperlowe** [otto8-ai/otto8#691]
Steps to Reproduce:
1. Navigate to `/agents/<agent>` page
2. click `+ Add Tool`
3. Catalog appears
4. hover over any non-selcted item in the catalog

Expected result:
A tooltip appears with the tool icon in it's original color

Actual result:
The tooltip appears with the tool icon with it's color inverted

![Image](https://github.com/user-attachments/assets/332acbd5-a74d-4331-9b95-c2c5a3ab63f5)

**Comment by sangee2004** [comment]
This issue is not seen when testing with version - `v0.0.0-dev-52278dcb-dirty`
