### ISSUE TITLE
UI - Added models appear as an id when setting the  Default Model Aliases. 

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#701]
**Steps to reproduce the problem:**
1. Add models using "Add Model" option in `Models` page.
2. Use "Default Model Aliases" to set the newly added model as default.

Notice that the newly added model shows up as an id in the  model alias dropdown list

<img width="641" alt="Screenshot 2024-11-26 at 2 20 29 PM" src="https://github.com/user-attachments/assets/7b9c5348-72f1-48ea-ba7a-84a1e69674c8">

If there is more than 1 LLM model added, then there is no way to tell which model is picked in this case

<img width="637" alt="Screenshot 2024-11-26 at 2 21 35 PM" src="https://github.com/user-attachments/assets/16a318bb-8b4e-4efb-a380-0b612242f0a4">

**Expected Behavior:**
Provide the names of the model in the model alias dropdown list.

**Comment by ryanhopperlowe** [comment]
Fixed by #767

**Comment by sangee2004** [comment]
Model names are provided now when setting Default Model aliases.
There is problem with not being able to  figure out which model provider I am picking when a model is selected in `Default Model Aliases` which is tracked in https://github.com/otto8-ai/otto8/issues/778
