### ISSUE TITLE
knowledge - how to handle embedding models yielding higher dimensional vectors than what pgvector supports?

### ISSUE THREAD

**Issue by iwilltry42** [otto8-ai/otto8#714]
- e.g. OpenAI's text-embedding-3-large yields vectors up to 3072 dimensions

Here's the issue on pgvector regarding that limitation: https://github.com/pgvector/pgvector/issues/461

**Comment by sanjay920** [comment]
only retaining the first 2000 dims should be okay since the text-embedding-3 models use Matryoshka representation - which allow you to shorten embedding length without sacrificing much WRT retrieval quality
I haven't come across an example where shortening the embedding (for `text-embedding-3-large`) has yielded worse results in semantic search vs not shortening

**Comment by iwilltry42** [comment]
@sanjay920 that's what we figured as well based on our past discussions.
I was wondering if we should maintain a list of models where this is supported.
E.g. for OpenAI's models you can pass an API param asking to truncate server-side (or just generate less-dimensional?) vs. cutting of the last entries on our side.

**Comment by sanjay920** [comment]
Did some investigation. Other than OpenAI's `text-embedding-3-large` we should be fine in terms of pgvectors dimension limit

| Provider           	| Model                           	| Vector Dimensions 	| Notes                      	| Matryoshka       	|
|--------------------	|---------------------------------	|-------------------	|----------------------------	|------------------	|
| OpenAI             	| text-embedding-3-small          	| 1536              	| Latest model               	| Yes              	|
|                    	| text-embedding-3-large          	| 3072              	| Latest model               	| Yes              	|
|                    	| text-embedding-ada-002          	| 1536              	| Legacy model               	| No               	|
| Cohere             	| embed-english-v3.0              	| 1024              	| Latest model               	| No               	|
|                    	| embed-multilingual-v3.0         	| 1024              	| Multilingual support       	| No               	|
|                    	| embed-english-light-v3.0        	| 384               	| Lightweight version        	| No               	|
|                    	| embed-multilingual-light-v3.0   	| 384               	| Lightweight multilingual   	| No               	|
|                    	| embed-english-v2.0              	| 4096              	| Legacy model               	| No               	|
|                    	| embed-english-light-v2.0        	| 1024              	| Legacy model               	| No               	|
|                    	| embed-multilingual-v2.0         	| 768               	| Legacy model               	| No               	|
| Mistral            	| mistral-embed                   	| 1024              	|                            	| No               	|
| Ollama             	| Various (model dependent)       	| Model dependent   	| Via Ollama API             	| Depends on model 	|
| LocalAI            	| Various (model dependent)       	| Model dependent   	| Self-hosted solution       	| Depends on model 	|
| Vertex AI (Google) 	| textembedding-gecko@003         	| 768               	|                            	| No               	|
|                    	| text-embedding-005              	| 768               	| Latest model               	| Yes              	|
|                    	| text-multilingual-embedding-002 	| 768               	| Latest multi-lingual model 	| Yes              	|
| Jina               	| jina-clip-v2                    	| 1024              	|                            	| Yes              	|
|                    	| jina-embeddings-v3              	| 1024              	|                            	| Yes              	|

**Comment by sanjay920** [comment]
Testing OpenAI Embedding API speed: reduce dimensionality for Matryoshka output embeddings vs no reduction

```
% python test_openai_embeddings.py 
Starting embedding API speed test...
Testing without dimensions: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:33<00:00,  1.50it/s]
Testing with dimensions: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 50/50 [00:28<00:00,  1.73it/s]

Results (in seconds):
         Standard Embedding  With Dimensions Reduced
Average               0.560            0.474
Median                0.452            0.407
Min                   0.169            0.121
Max                   2.244            1.947
Std Dev               0.394            0.332

Percentage difference in average time: -15.41%
```
Test Source: https://gist.github.com/sanjay920/968964bf17293fcd8a20068f28e014d8

It looks like specifying reduced embedding dimensions actually decreases latency - probably because the response payload is smaller (2000 float values vs 3072) and that has snowballing implications: less to be serialized on openais end, less data transferred over network, and less data deserialized on user's end.

**Comment by iwilltry42** [comment]
Nice one!
FWIW, Donnie has been working with VoyageAI embeddings recently.
However, they only have one model that **may** yield >2k dimensions and also their future models will be trained with Matryoshka (according to forum posts), so they're no concern either: https://docs.voyageai.com/docs/embeddings

**Comment by iwilltry42** [comment]
Sanjay merged a couple of changes addressing this - there shouldn't be any noticeable change, as we were able to use -large before without error - now it's just cleanly implemented.
Thanks @sanjay920

**Comment by sangee2004** [comment]
` text-embedding-3-large` is the suggested default for `Text Embedding (Knowledge)`.
I have been able to ingest knowledge files successfully and knowledge retrievals are also working fine.
