### ISSUE TITLE
Knowlege - Onedrive Sync -  Using `CopyLink` option for onedrive links does not work sometimes.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#717]
**Steps to reproduce the problem:**
1. Create an agent with knowledge from onedrive link.
2. Enter the value that you get from `Copy link` option for the one drive folder we want to sync (from onedrive UI) as the Link URL

Sync will fail with following error-
`failed to sync onedrive links, error: The sharing link no longer exists, or you do not have permission to access it.`

**Note** - I have seen the link from `Copy link` option work many times. But there are some times when this link does not work. 

The times i have not seen it work is when `Copy link` url was in this format which has the folder name - 

`https://<server url>/my?id=%2Fpersonal%2F<username>%5F<domain>?%5Fio%2FDocuments%2FTestLinks&ga=1`

When it works , it is of this format -
 `<server-url>/:f:/g/personal/<username>_<domain>_io/EqcO0rMpvDBKtdDODpVqWJoBjhE8RRnznTJdNNdt67jdbw?e=RZSFsK`

Using `Share Link` always works.

**Comment by cjellick** [comment]
@sangee2004 are you able to provide an actual specific link that at least fails sometimes?

**Comment by cjellick** [comment]
If a link doesn't work, does it consistently not work forever or will it randmonly start working?

**Comment by sangee2004** [comment]
If it fails , it always consistently fails. I will provide one that fails always in a bit.

**Comment by cjellick** [comment]
@StrongMonkey you are working on this, right?

**Comment by StrongMonkey** [comment]
I am adding docs to provide a clear instruction on how to generate onedrive link. For other issues, I do think it might be a user error and need more investigation if @sangee2004 can reliably reproduce

**Comment by StrongMonkey** [comment]
@sangee2004 I am moving to testing since this can't be reproduced, but I have added docs on how to generate onedrive link when adding the source

**Comment by sangee2004** [comment]
We are now provided with instruction on how to get the folder link which points to microsoft document relating to using share link.
![Image](https://github.com/user-attachments/assets/35f9bb0e-48d9-4a30-a554-3b10a00360ca)
