### ISSUE TITLE
Knowledge - Unsupported status count is not bubbled up at the folder level.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#718]
**Steps to reproduce the problem:**
1. Create an agent with knowledge files from one drive folder that has unsupported file types like `xlsx`
2. Once folder is synced , ingest all files.

Notice that  unsupported status count is not bubbled up at the folder level.

<img width="940" alt="Screenshot 2024-11-27 at 2 28 51 PM" src="https://github.com/user-attachments/assets/2a4e02aa-f9a3-492b-b746-31ed49b138b4">

The only way to find out why there is a mismatch between ingested count and synced file count, is to actually drill down to the folder that had the file that shows `Unsupported` state.

Expected Behavior:
Unsupported status count is not bubbled up at the folder level.

**Comment by StrongMonkey** [comment]
The reason we didn't add the unsupported files is because it will makes the panel looks too busy... but since you already added we will see how it looks.

**Comment by iwilltry42** [comment]
Heh, @cjellick asked me to browse through the open issues and since I didn't see anything on this one, I just gave it a go :)

I figured the same though and raised the point to Craig earlier.
I proposed we just use icons with mouseover/hover descriptions instead.

**Comment by sangee2004** [comment]
"Unsupported" count now bubbles up in at folder level.
<img width="833" alt="Image" src="https://github.com/user-attachments/assets/a38646cb-09b7-4173-b61f-cfef9aa925ae" />
