### ISSUE TITLE
UI - Webhook - Prepopulate `Payload Signature Header` when `Payload Signature Secret` is entered.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#728]
**Steps to reproduce the problem:**
1. When creating webhooks , enter `Payload Signature Secret` and create a webhook.

Notice that user is presented with message `webhook must have secret and header set together`

**Expected Behavior:**
Can we have the  `Payload Signature Header` defaulted to `X-Hub-Signature-256` when  `Payload Signature Secret` is entered ?

**Comment by cjellick** [comment]
That header `X-Hub-Signature-256` is specific to just github. it will be different for every webhook provider. It doesnt make sense to me to set it to github's value
