### ISSUE TITLE
UI - Workflow credential - Provide easier way to enter credentials (may be drop down of tool name that requires auth).

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#732]
**Steps to reproduce the problem:**
1.  Create a workflow with credential.
2. Notice that I have to enter a credential as a tool url to a specific tool's credential  like - `github.com/otto8-ai/tools/github/credential`.

**Expected Behavior:**
Having to enter credential as a tool url to a specific tool's credential  is error prone. 
Can we provide a drop down option with all tools (that require credentials) that user can pick instead?

**Comment by cjellick** [comment]
not changing this.
