### ISSUE TITLE
UI - Delete knowledge source continue to be shown in Agent edit view (until manually refreshed or you quit agent and re vist it)

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#746]
**Steps to reproduce the problem:**
1. Create an agent with knowledge files from notion or  one drive location.
2. Wait for initial sync to be completed.
3. Close the knowledge page.
4. Delete the knowledge entry.
Notice that the knowledge continues to be present.
5. Refresh the page.
It continues to be present.
6. Quit the Agent edit view and relaunch the edit view for the agent again.
Notice that the knowledge is not present anymore.

Note - Sometimes I see the deleted knowledge entry getting removed on manual refresh in step 5.

https://github.com/user-attachments/assets/7dfb8794-2708-498b-887c-a24cbd96b630

**Comment by StrongMonkey** [comment]
It is probably the finalizer that is preventing it to be deleted. I can fix that on the client side to not show it.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest build.
