### ISSUE TITLE
UI - Allow the user to chat with an agent thread in the thread view

### ISSUE THREAD

**Issue by ryanhopperlowe** [otto8-ai/otto8#756]
As an admin user, I should be able to chat with an agent from the thread view. This does not apply to workflow threads.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Chat component to allow chatting with agents in the thread view. Added a condition to show the Chatbar for agent threads that are not read-only.

You can review changes in this commit: https://github.com/mnmnk43434/otto8-ai-otto8-756/commit/a2245a7686b867cef469f63450edfc089b5b0201.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by sangee2004** [comment]
Able to chat with agent threads in thread view.
