### ISSUE TITLE
Knowledge - When Syncing/ingestion is in progress , UI becomes unresponsive and very sluggish.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#768]
**Note** - I am testing this in test env which has lot of agents.
**Steps to reproduce the problem:**
1. Create an agent with knowledge from one drive location lot of files - 600+ files in my case.
2. Wait for all the files to be synced.
3. Ingest all files.
Notice that UI becomes unresponsive and  very sluggish when syncing is in progress.

https://github.com/user-attachments/assets/613f5755-0244-40fe-8ba7-3532aea7338a

After few minutes (even when sync is in progress), it recovers from this state. I am able to load the agent list page and work with the UI even though it is slow to respond.

**Note** - The same behavior is also seen when I exclude all files (after they have all been ingested). During the time when the files are getting unapproved , UI becomes unresponsive.

**Comment by sangee2004** [comment]
The same behavior with UI becoming  sluggish is also noted when syncing is in progress.

I see the issue with not being able to list agents ("No results" gets returned and then eventually agent list is presented).

https://github.com/user-attachments/assets/13651eaf-1f2a-4bc1-9a4f-eec047021cd0

UI starts becoming responsive again after the few glitches encountered.

**Comment by StrongMonkey** [comment]
I just tried to ingest the same Corp doc and don't see this issue. The UI and api respond within normal timespan.

**Comment by StrongMonkey** [comment]
@sangee2004 I can't reproduce it. Did the same test in testing env and everything looks fine. Can you retest this and let me know if you are able to reproduce?

**Comment by sangee2004** [comment]
We just notice this happen when ingesting `corp docs` in test env.

**Comment by cjellick** [comment]
back to testing after the perf improvments

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest build in test env.
