### ISSUE TITLE
No Error message presented to user when listing model fails due to incorrect model configuration.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#785]
**Steps to reproduce the problem:**
1. Configure a model providers with incorrect values (In my case Azure OpenAI provider)
2. Using Models ->"Add Model" , add a model with Model provider set tot `Azure OpenAI provider`

Notice that no model is provided in the dropdown for  `Target Model`
<img width="666" alt="Screenshot 2024-12-05 at 10 18 25 AM" src="https://github.com/user-attachments/assets/0848fadf-6981-462a-a124-03f3aaddafb0">

I see the following errors in server logs

```
time="2024-12-05T18:16:28Z" level=info msg="Handled request: method POST, path /run" id=c1d04353-130d-4e86-bedc-f8a64ca1cb3b
DefaultAzureCredential failed to retrieve a token from the included credentials.
Attempted credentials:
	EnvironmentCredential: Authentication failed: Unable to get authority configuration for https://login.microsoftonline.com/bill-testing-things. Authority would typically be in a format of https://login.microsoftonline.com/your_tenant or https://tenant_name.ciamlogin.com or https://tenant_name.b2clogin.com/tenant.onmicrosoft.com/policy.  Also please double check your tenant name or GUID is correct.
To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```
**Expected Behavior:**
User should be presented with this error message.

**Comment by ivyjeong13** [comment]
I believe this issue is no longer valid as a user can no longer create a model (models back populated with model provider)

**Comment by sangee2004** [comment]
There is no "Create Model" page anymore since models get auto created on successful configuration of model providers.
