### ISSUE TITLE
Configuration changes made to provider does not take effect until a hard refresh is done in the "Add Model" page.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#786]
**Steps to reproduce the problem:**

1. Configure a model providers with incorrect values (In my case Azure OpenAI provider)
2. Using Models ->"Add Model" , add a model with Model provider set tot Azure OpenAI provider
3. Notice that no model is provided in the dropdown for `Target Model` since model provider configuration is incorrect.
4. Go to `Model Providers` tab and reconfigure ` Azure OpenAI provider` with right values.
5. Try to add a model again using Models ->"Add Model" , add a model with Model provider set tot Azure OpenAI provider
Notice that user will still be presented with an empty  model list when selecting  `Target Model`
<img width="666" alt="Screenshot 2024-12-05 at 10 18 25 AM" src="https://github.com/user-attachments/assets/6fd639c7-bcdc-4e52-b926-554af7a43965">

After a manual Refresh , we see the model list for `Target Model` being populated.

**Expected Behavior:**
We should not have to do a manual refresh in this case.

**Comment by ivyjeong13** [comment]
I believe this issue is invalid as we no longer allow adding of models with the model provider changes.

**Comment by sangee2004** [comment]
Closing this issue.  There is no "Add Model" Page in the latest version. Models get auto populated on successful configuration of model providers.
