### ISSUE TITLE
Provide horizontal scroll bar for `Azure OpenAI` configuration page.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#790]
**Steps to reproduce the problem:**
1. Go to Model Providers-> Azure OpenAI and click on "Settings".

Notice that "Set Up Azure OpenAI" page gets truncated and not fully presented unless we are in in Full Screen Mode.
In this case `Confirm` button is hidden.

<img width="1312" alt="Screenshot 2024-12-05 at 12 58 47 PM" src="https://github.com/user-attachments/assets/6d5ffe4c-eb8b-415c-b5e4-93bdd58d983d">

**Expected Behavior:**
Provide horizontal scroll bar for `Azure OpenAI` configuration page.

**Comment by ivyjeong13** [comment]
<img width="680" alt="Image" src="https://github.com/user-attachments/assets/77405b6a-8179-42bc-ac0e-20e4fd54fb73" />

Should be addressed now! More user friendly labels and scroll bar to keep confirm button from being unreachable!

**Comment by sangee2004** [comment]
Horizontal scrollbar is now available in Azure OpenAI configuration page.
