### ISSUE TITLE
Threads - Only some thread entries are listed when there are lot of threads and when you have few threads they end up using the entire area .

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#801]
**Steps to reproduce the problem:**

Scenario 1:

1. Create few agents and have  couple of conversation in new threads.

In my case there are only 2 threads.

Notice that the display of threads ends up using the entire area .
<img width="1184" alt="Screenshot 2024-12-06 at 12 04 58 PM" src="https://github.com/user-attachments/assets/91188bdd-71e8-4d66-ba8b-9e7a2083e48f">

Scenario 2:
This is seen in `test` env where there are lot of threads from last 1 month.
1. Go to threads view.

Only very few threads get returned. I can see a max of 13 most recent threads if i am on full screen. I am seeing lesser than 13 entries when screen size is smaller.

**Comment by thedadams** [comment]
This issue seems to be addressed in the test environment. Moving to "Testing" for verification.

**Comment by sangee2004** [comment]
This issue is not seen anymore when testing with latest builds.
