### ISSUE TITLE
When configuring Azure OpenAI provider, all configuration parameters are hidden (**) including the ones that are not passwords.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#817]
**Steps to reproduce the problem:**
1. Configure Azure Open AI
2. Notice that all configuration parameters are hidden (**) including the ones that are not passwords.
<img width="797" alt="Screenshot 2024-12-06 at 7 38 30 PM" src="https://github.com/user-attachments/assets/8d9925dd-f0e9-4f53-a943-d9bbfbfc61dd">

**Expected Behavior:**
Parameters like endpoint ,resource group should not be hidden.
There may be few other configurations like client id, subscription id and tenant id that may also not be hidden. Not sure if these fields need to be clear text or hidden.

**Comment by ivyjeong13** [comment]
I believe this has been resolved! Moving to testing for verification.

**Comment by sangee2004** [comment]
`Client Secret` is the only field that is presented with password masking.
All other parameters are presented in clear text as expected.
