### ISSUE TITLE
Should not be allowed to chat with inactive models.

### ISSUE THREAD

**Issue by sangee2004** [otto8-ai/otto8#847]
**Steps to reproduce the problem:**

1. Configure OpenAI model provider.
2. Create an agent with model set to `gpt-3.5-turbo-16k`
3. Make this models - `gpt-3.5-turbo-16k` inactive.
4. Start a conversation with the agent created in step 2.

We are able to get a responses for the chat message using - `gpt-3.5-turbo-16k` 

**Expected Behavior:**
We should not be allowed to chat using inactive models.

**Comment by thedadams** [comment]
The change for the backend has been merged.

**Comment by sangee2004** [comment]
Following error message is presented to user when testing with latest builds.
```
failed to run: failed calling model for completion: error, status code: 502, message: failed to get model: model "gpt-3.5-turbo" is not active
```
